[package]
description = "Connector library for the flattiverse.com game server."
homepage = "https://www.flattiverse.com/"
name = "flattiverse_connector"
version = "36.0.2"
authors = ["Michael Watzko <michael@watzko.de>"]
keywords = ["connector", "flattiverse"]
categories = ["games", "network-programming"]
license = "MIT"

[lib]

[dependencies]
byteorder = "1.1.0"
sha2 = "0.6.0"
chrono = "0.4.0"
hostname = "0.1.3"
flate2 = "0.2.19"
backtrace = "0.3.3"
rand = "0.3.16"
