[package]
description = "Connector library for the flattiverse.com game server."
homepage = "https://www.flattiverse.com/"
repository = "https://github.com/flattiverse/connector-rust.git"
name = "flattiverse_connector"
version = "0.0.0"
authors = ["Michael Watzko <michael@watzko.de>"]
keywords = ["connector", "flattiverse"]
categories = ["games", "network-programming"]
license = "MIT"
edition = "2021"

[lib]

[dependencies]
log = "0.4.17"
thiserror = "1.0.38"
tokio = { version = "1.24.2", features = ["net", "sync", "time", "rt", "macros"] }
tokio-tungstenite = { version = "0.18.0", features = ["rustls", "rustls-tls-native-roots"] }
futures = "0.3.25"
futures-util = "0.3.25"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
nohash-hasher = "0.2.0"
derive_more = { version = "0.99.17", features = ["from"] }
strum_macros = "0.24.3"
crossbeam = "0.8.2"
async-http-proxy = { version = "1.2.5", features = ["runtime-tokio"] }
url = "2.3.1"

[dev-dependencies]
tokio = { features = ["rt-multi-thread"] }