[package]
description = "Connector library for the flattiverse.com game server."
homepage = "https://www.flattiverse.com/"
name = "flattiverse_connector"
version = "0.0.0"
authors = ["Michael Watzko <michael@watzko.de>"]
keywords = ["connector", "flattiverse"]
categories = ["games", "network-programming"]
license = "MIT"
edition = "2018"

[lib]

[dependencies]
tokio = "0.2.0-alpha.5"
bytes = "0.4.12"
aes = "0.3.2"
block-modes = "0.3.3"
sha2 = "0.8.0"
byteorder = "1.3.2"
rand = "0.7.2"
futures-util = { package = "futures-util-preview", version = "0.3.0-alpha.17" }


[profile.release]
lto = true