[package]
description = "Connector library for the flattiverse.com game server."
homepage = "https://www.flattiverse.com/"
repository = "https://github.com/flattiverse/connector-rust.git"
name = "flattiverse_connector"
version = "0.0.0"
authors = ["Michael Watzko <michael@watzko.de>"]
keywords = ["connector", "flattiverse"]
categories = ["games", "network-programming"]
license = "MIT"
edition = "2018"

[lib]

[dependencies]
tokio = "0.2.0-alpha.6"
bytes = "0.4"
aes = "0.3"
block-modes = "0.3"
sha2 = "0.8"
byteorder = "1.3"
rand = "0.7"
futures-util = { package = "futures-util-preview", version = "0.3.0-alpha.19" }
log = "0.4"
num-traits = "0.2.8"
num-derive = "0.3.0"
backtrace = "0.3.38"

log4rs = "0.8"

[profile.release]
lto = true
