[package]
description = "Connector library for the flattiverse.com game server."
homepage = "https://www.flattiverse.com/"
repository = "https://github.com/flattiverse/connector-rust.git"
name = "flattiverse_connector"
version = "0.0.0"
authors = ["Michael Watzko <michael@watzko.de>"]
keywords = ["connector", "flattiverse"]
categories = ["games", "network-programming"]
license = "MIT"
edition = "2018"

[lib]

[dependencies]
futures = "0.3.1"
futures-util = { package = "futures-util-preview", version = "0.3.0-alpha" }
bytes = "0.4"
aes = "0.3"
block-modes = "0.3"
sha2 = "0.8"
byteorder = "1.3"
rand = "0.7"
log = "0.4"
num-traits = "0.2"
num-derive = "0.3"
backtrace = "0.3"
log4rs = { version = "0.8", optional = true }
tokio = { version = "0.2.0-alpha", optional = true }
wasm-bindgen = {version = "0.2.55", optional = true }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  "ErrorEvent",
  "MessageEvent",
  "WebSocket",
  "TcpSocket",
]
optional = true

[features]
default = ["log4rs", "tokio"]
wasm = ["wasm-bindgen", "web-sys"]

[profile.release]
lto = true
