
#[repr(u8)]
pub enum Task {
    DidAvatar = 0,
    DidConnect = 1,
    DidJoin = 2,
    DidRegisterShip =3,
    DidChatGlobal = 4,
    DidChatAccount = 5,
    DidScan = 6,
    DidMultiScan = 7,
    DidMove = 8,
    DidShoot = 9,
    DidCollectNebula = 10,
    DidProduceCrystal = 11,
    DidUseTractorbeam = 12,
    DidUseEnergytransfer = 13,
    DidUseBuild = 14,
    UsedVector = 16,
    UsedMessages = 17,
    UsedCorona = 18,
    UsedBuoyMessage = 19,
    UsedSequence = 20,
    UsedShotStats = 21,
    UsedOrbits = 22,
    UsedChangelog = 23,
    UsedTournament = 24,
    UsedControllableInfo = 25,
    UsedAvatar = 26,
    UsedPlayers = 27,
    UsedAvgCommitTime = 28,
    UsedPlatform = 29,
    UsedPolynominal = 30,
}